server:
  port: 61002
  max-http-header-size: 10240
eureka:
  client:
    serviceUrl:
      defaultZone: http://happymix:20190415@localhost:8761/eureka
  instance:
    lease-expiration-duration-in-seconds: 10  #超过多少时间删除服务
    lease-renewal-interval-in-seconds: 5    #设置心跳时长
spring:
  redis:
    database: 0
    timeout: 10000
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 123456
    # 连接池最大连接数（使用负值表示没有限制）
    pool:
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
  datasource:
    name: dev
    url: jdbc:mysql://localhost:3306/happy_mix_vip_user?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 5
    maxWait: 60000
    minIdle: 10
    timeBetweenEvictionRunsMillis: 2000
    minEvictableIdleTimeMillis: 600000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
mapper:
  mappers:
  - tk.mybatis.mapper.common.Mapper
  not-empty: false
  identity: MYSQL
mybatis:
  mapperLocations: classpath:mappers/*.xml
  typeAliasesPackage: cn.lfn.happy.mix.entity
